contraction_mapping = {
    "ain't": "is not",
    "aren't": "are not",
    "can't": "cannot",
    "'cause": "because",
    "could've": "could have",
    "couldn't": "could not",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "hadn't": "had not",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he would",
    "he'll": "he will",
    "he's": "he is",
    "how'd": "how did",
    "how'd'y": "how do you",
    "how'll": "how will",
    "how's": "how is",
    "I'd": "I would",
    "I'd've": "I would have",
    "I'll": "I will",
    "I'll've": "I will have",
    "I'm": "I am",
    "I've": "I have",
    "i'd": "i would",
    "i'd've": "i would have",
    "i'll": "i will",
    "i'll've": "i will have",
    "i'm": "i am",
    "i've": "i have",
    "isn't": "is not",
    "it'd": "it would",
    "it'd've": "it would have",
    "it'll": "it will",
    "it'll've": "it will have",
    "it's": "it is",
    "let's": "let us",
    "ma'am": "madam",
    "mayn't": "may not",
    "might've": "might have",
    "mightn't": "might not",
    "mightn't've": "might not have",
    "must've": "must have",
    "mustn't": "must not",
    "mustn't've": "must not have",
    "needn't": "need not",
    "needn't've": "need not have",
    "o'clock": "of the clock",
    "oughtn't": "ought not",
    "oughtn't've": "ought not have",
    "shan't": "shall not",
    "sha'n't": "shall not",
    "shan't've": "shall not have",
    "she'd": "she would",
    "she'd've": "she would have",
    "she'll": "she will",
    "she'll've": "she will have",
    "she's": "she is",
    "should've": "should have",
    "shouldn't": "should not",
    "shouldn't've": "should not have",
    "so've": "so have",
    "so's": "so as",
    "this's": "this is",
    "that'd": "that would",
    "that'd've": "that would have",
    "that's": "that is",
    "there'd": "there would",
    "there'd've": "there would have",
    "there's": "there is",
    "here's": "here is",
    "they'd": "they would",
    "they'd've": "they would have",
    "they'll": "they will",
    "they'll've": "they will have",
    "they're": "they are",
    "they've": "they have",
    "to've": "to have",
    "wasn't": "was not",
    "we'd": "we would",
    "we'd've": "we would have",
    "we'll": "we will",
    "we'll've": "we will have",
    "we're": "we are",
    "we've": "we have",
    "weren't": "were not",
    "what'll": "what will",
    "what'll've": "what will have",
    "what're": "what are",
    "what's": "what is",
    "what've": "what have",
    "when's": "when is",
    "when've": "when have",
    "where'd": "where did",
    "where's": "where is",
    "where've": "where have",
    "who'll": "who will",
    "who'll've": "who will have",
    "who's": "who is",
    "who've": "who have",
    "why's": "why is",
    "why've": "why have",
    "will've": "will have",
    "won't": "will not",
    "won't've": "will not have",
    "would've": "would have",
    "wouldn't": "would not",
    "wouldn't've": "would not have",
    "y'all": "you all",
    "y'all'd": "you all would",
    "y'all'd've": "you all would have",
    "y'all're": "you all are",
    "y'all've": "you all have",
    "you'd": "you would",
    "you'd've": "you would have",
    "you'll": "you will",
    "you'll've": "you will have",
    "you're": "you are",
    "you've": "you have",
}


chat_words_replacements = {
    # Common Chat Words
    "np": "no problem",
    "tho": "though",
    "cuz": "because",
    "gonna": "going to",
    "wanna": "want to",
    "gotta": "got to",
    "kinda": "kind of",
    "sorta": "sort of",
    "lemme": "let me",
    "gimme": "give me",
    "ain't": "am not/is not/are not",
    "wth": "what the hell",
    "omfg": "oh my fucking god",
    "gtg": "got to go",
    "ttyl": "talk to you later",
    "afaik": "as far as I know",
    "bday": "birthday",
    # Review related Words
    "awesome": "extremely good",
    "amazing": "astonishing",
    "awful": "terrible",
    "terrible": "horrible",
    "excellent": "outstanding",
    "fantastic": "extraordinary",
    "brilliant": "superb",
    "horrendous": "dreadful",
    "magnificent": "splendid",
    "phenomenal": "remarkable",
    "subpar": "below average",
    "mediocre": "average",
    "impressive": "striking",
    "disappointing": "unsatisfying",
    "satisfactory": "adequate",
    "stellar": "exceptional",
    "flawless": "perfect",
    "overrated": "overestimated",
    "underrated": "underestimated",
    # Expressions
    "btw": "by the way",
    "fyi": "for your information",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "lol": "laughing out loud",
    "rofl": "rolling on the floor laughing",
    "omg": "oh my god",
    "omfg": "oh my fucking god",
    "wtf": "what the fuck",
    "gtfo": "get the fuck out",
    "fomo": "fear of missing out",
    "yolo": "you only live once",
    "irl": "in real life",
    "bff": "best friends forever",
}

airport_codes = {
    # Africa
    "JNB": "OR Tambo International Airport (Johannesburg, South Africa)",
    "CAI": "Cairo International Airport (Cairo, Egypt)",
    "LOS": "Murtala Muhammed International Airport (Lagos, Nigeria)",
    "NBO": "Jomo Kenyatta International Airport (Nairobi, Kenya)",
    "CPT": "Cape Town International Airport (Cape Town, South Africa)",
    "DUR": "King Shaka International Airport (Durban, South Africa)",
    "CMN": "Mohammed V International Airport (Casablanca, Morocco)",
    "ADD": "Addis Ababa Bole International Airport (Addis Ababa, Ethiopia)",
    "ALG": "Houari Boumediene Airport (Algiers, Algeria)",
    "ACC": "Kotoka International Airport (Accra, Ghana)",
    
    # Asia
    "SIN": "Singapore Changi Airport (Singapore)",
    "HKG": "Hong Kong International Airport (Hong Kong)",
    "PEK": "Beijing Capital International Airport (Beijing, China)",
    "BKK": "Suvarnabhumi Airport (Bangkok, Thailand)",
    "NRT": "Narita International Airport (Tokyo, Japan)",
    "KUL": "Kuala Lumpur International Airport (Kuala Lumpur, Malaysia)",
    "DEL": "Indira Gandhi International Airport (New Delhi, India)",
    "ICN": "Incheon International Airport (Seoul, South Korea)",
    "CGK": "Soekarno Hatta International Airport (Jakarta, Indonesia)",
    "PVG": "Shanghai Pudong International Airport (Shanghai, China)",
    "MNL": "Ninoy Aquino International Airport (Manila, Philippines)",
    "DXB": "Dubai International Airport (Dubai, United Arab Emirates)",
    "IST": "Istanbul Atatürk Airport (Istanbul, Turkey)",
    "SYD": "Sydney Airport (Sydney, Australia)",
    "HND": "Haneda Airport (Tokyo, Japan)",
    "CAN": "Guangzhou Baiyun International Airport (Guangzhou, China)",
    "SVO": "Sheremetyevo International Airport (Moscow, Russia)",
    "TPE": "Taiwan Taoyuan International Airport (Taipei, Taiwan)",
    "BOM": "Chhatrapati Shivaji International Airport (Mumbai, India)",
    # Europe
    "LHR": "London Heathrow Airport (London, United Kingdom)",
    "CDG": "Charles de Gaulle Airport (Paris, France)",
    "FRA": "Frankfurt Airport (Frankfurt, Germany)",
    "AMS": "Amsterdam Airport Schiphol (Amsterdam, Netherlands)",
    "BCN": "Barcelona El Prat Airport (Barcelona, Spain)",
    "FCO": "Leonardo da Vinci Fiumicino Airport (Rome, Italy)",
    "MAD": "Adolfo Suárez Madrid Barajas Airport (Madrid, Spain)",
    "IST": "Istanbul Atatürk Airport (Istanbul, Turkey)",
    "MUC": "Munich Airport (Munich, Germany)",
    "ZRH": "Zurich Airport (Zurich, Switzerland)",
    "CPH": "Copenhagen Airport (Copenhagen, Denmark)",
    "ATH": "Athens International Airport (Athens, Greece)",
    "VIE": "Vienna International Airport (Vienna, Austria)",
    "ARN": "Stockholm Arlanda Airport (Stockholm, Sweden)",
    "WAW": "Warsaw Chopin Airport (Warsaw, Poland)",
    "OSL": "Oslo Airport (Oslo, Norway)",
    
    # North America
    "ATL": "Hartsfield Jackson Atlanta International Airport (Atlanta, USA)",
    "LAX": "Los Angeles International Airport (Los Angeles, USA)",
    "ORD": "O'Hare International Airport (Chicago, USA)",
    "DFW": "Dallas/Fort Worth International Airport (Dallas, USA)",
    "DEN": "Denver International Airport (Denver, USA)",
    "JFK": "John F. Kennedy International Airport (New York City, USA)",
    "SFO": "San Francisco International Airport (San Francisco, USA)",
    "LAS": "McCarran International Airport (Las Vegas, USA)",
    "MIA": "Miami International Airport (Miami, USA)",
    "YYZ": "Toronto Pearson International Airport (Toronto, Canada)",
    "YVR": "Vancouver International Airport (Vancouver, Canada)",
    "CUN": "Cancún International Airport (Cancún, Mexico)",
    "MEX": "Mexico City International Airport (Mexico City, Mexico)",
    "PTY": "Tocumen International Airport (Panama City, Panama)",
    "SJU": "Luis Muñoz Marín International Airport (San Juan, Puerto Rico)",
    "HAV": "José Martí International Airport (Havana, Cuba)",
    
    # South America
    "GRU": "São Paulo Guarulhos International Airport (São Paulo, Brazil)",
    "EZE": "Ministro Pistarini International Airport (Buenos Aires, Argentina)",
    "BOG": "El Dorado International Airport (Bogotá, Colombia)",
    "SCL": "Comodoro Arturo Merino Benítez International Airport (Santiago, Chile)",
    "LIM": "Jorge Chávez International Airport (Lima, Peru)",
    "GIG": "Rio de Janeiro Galeão International Airport (Rio de Janeiro, Brazil)",
    "UIO": "Mariscal Sucre International Airport (Quito, Ecuador)",
    "SJO": "Juan Santamaría International Airport (San José, Costa Rica)",
    "UIO": "Mariscal Sucre International Airport (Quito, Ecuador)",
    "ASU": "Silvio Pettirossi International Airport (Asunción, Paraguay)",
    "LAD": "Quatro de Fevereiro International Airport (Luanda, Angola)",
    "PTY": "Tocumen International Airport (Panama City, Panama)",
    "BOG": "El Dorado International Airport (Bogotá, Colombia)",
    "LIM": "Jorge Chávez International Airport (Lima, Peru)",
    
    # Oceania
    "SYD": "Sydney Airport (Sydney, Australia)",
    "MEL": "Melbourne Airport (Melbourne, Australia)",
    "BNE": "Brisbane Airport (Brisbane, Australia)",
    "AKL": "Auckland Airport (Auckland, New Zealand)",
    "CHC": "Christchurch International Airport (Christchurch, New Zealand)",
    "PER": "Perth Airport (Perth, Australia)",
    "ADL": "Adelaide Airport (Adelaide, Australia)",
    "MNL": "Ninoy Aquino International Airport (Manila, Philippines)",
    "HNL": "Daniel K. Inouye International Airport (Honolulu, USA)",
    "NOU": "La Tontouta International Airport (Nouméa, New Caledonia)",
    "PPT": "Fa'a'ā International Airport (Papeete, French Polynesia)",
    "NAN": "Nadi International Airport (Nadi, Fiji)",
    "GUM": "Antonio B. Won Pat International Airport (Guam)",
    "RAR": "Rarotonga International Airport (Rarotonga, Cook Islands)",
    "APW": "Faleolo International Airport (Apia, Samoa)"
}