contraction_mapping = {
    "ain't": "is not",
    "aren't": "are not",
    "can't": "cannot",
    "'cause": "because",
    "could've": "could have",
    "couldn't": "could not",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "hadn't": "had not",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he would",
    "he'll": "he will",
    "he's": "he is",
    "how'd": "how did",
    "how'd'y": "how do you",
    "how'll": "how will",
    "how's": "how is",
    "I'd": "I would",
    "I'd've": "I would have",
    "I'll": "I will",
    "I'll've": "I will have",
    "I'm": "I am",
    "I've": "I have",
    "i'd": "i would",
    "i'd've": "i would have",
    "i'll": "i will",
    "i'll've": "i will have",
    "i'm": "i am",
    "i've": "i have",
    "isn't": "is not",
    "it'd": "it would",
    "it'd've": "it would have",
    "it'll": "it will",
    "it'll've": "it will have",
    "it's": "it is",
    "let's": "let us",
    "ma'am": "madam",
    "mayn't": "may not",
    "might've": "might have",
    "mightn't": "might not",
    "mightn't've": "might not have",
    "must've": "must have",
    "mustn't": "must not",
    "mustn't've": "must not have",
    "needn't": "need not",
    "needn't've": "need not have",
    "o'clock": "of the clock",
    "oughtn't": "ought not",
    "oughtn't've": "ought not have",
    "shan't": "shall not",
    "sha'n't": "shall not",
    "shan't've": "shall not have",
    "she'd": "she would",
    "she'd've": "she would have",
    "she'll": "she will",
    "she'll've": "she will have",
    "she's": "she is",
    "should've": "should have",
    "shouldn't": "should not",
    "shouldn't've": "should not have",
    "so've": "so have",
    "so's": "so as",
    "this's": "this is",
    "that'd": "that would",
    "that'd've": "that would have",
    "that's": "that is",
    "there'd": "there would",
    "there'd've": "there would have",
    "there's": "there is",
    "here's": "here is",
    "they'd": "they would",
    "they'd've": "they would have",
    "they'll": "they will",
    "they'll've": "they will have",
    "they're": "they are",
    "they've": "they have",
    "to've": "to have",
    "wasn't": "was not",
    "we'd": "we would",
    "we'd've": "we would have",
    "we'll": "we will",
    "we'll've": "we will have",
    "we're": "we are",
    "we've": "we have",
    "weren't": "were not",
    "what'll": "what will",
    "what'll've": "what will have",
    "what're": "what are",
    "what's": "what is",
    "what've": "what have",
    "when's": "when is",
    "when've": "when have",
    "where'd": "where did",
    "where's": "where is",
    "where've": "where have",
    "who'll": "who will",
    "who'll've": "who will have",
    "who's": "who is",
    "who've": "who have",
    "why's": "why is",
    "why've": "why have",
    "will've": "will have",
    "won't": "will not",
    "won't've": "will not have",
    "would've": "would have",
    "wouldn't": "would not",
    "wouldn't've": "would not have",
    "y'all": "you all",
    "y'all'd": "you all would",
    "y'all'd've": "you all would have",
    "y'all're": "you all are",
    "y'all've": "you all have",
    "you'd": "you would",
    "you'd've": "you would have",
    "you'll": "you will",
    "you'll've": "you will have",
    "you're": "you are",
    "you've": "you have",
    "ws": "was",
    "w": "with",
    "msg": "message",
    "ms": "miss",
    "u": "you",
    "ur": "your",
    "r": "are",
    "b": "be",
    "d": "the",
    "n": "and",
    "k": "ok",
    "kk": "ok",
    "missin": "missing",
    "mr": "mister",
    "mrs": "misses",
    "ms.": "miss",
}


chat_words_replacements = {
    # Common Chat Words
    "np": "no problem",
    "tho": "though",
    "cuz": "because",
    "gonna": "going to",
    "wanna": "want to",
    "gotta": "got to",
    "kinda": "kind of",
    "sorta": "sort of",
    "lemme": "let me",
    "gimme": "give me",
    "ain't": "am not/is not/are not",
    "wth": "what the hell",
    "omfg": "oh my fucking god",
    "gtg": "got to go",
    "ttyl": "talk to you later",
    "afaik": "as far as I know",
    "bday": "birthday",
    # Review related Words
    "awesome": "extremely good",
    "amazing": "astonishing",
    "awful": "terrible",
    "terrible": "horrible",
    "excellent": "outstanding",
    "fantastic": "extraordinary",
    "brilliant": "superb",
    "horrendous": "dreadful",
    "magnificent": "splendid",
    "phenomenal": "remarkable",
    "subpar": "below average",
    "mediocre": "average",
    "impressive": "striking",
    "disappointing": "unsatisfying",
    "satisfactory": "adequate",
    "stellar": "exceptional",
    "flawless": "perfect",
    "overrated": "overestimated",
    "underrated": "underestimated",
    # Expressions
    "btw": "by the way",
    "fyi": "for your information",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "lol": "laughing out loud",
    "rofl": "rolling on the floor laughing",
    "omg": "oh my god",
    "omfg": "oh my fucking god",
    "wtf": "what the fuck",
    "gtfo": "get the fuck out",
    "fomo": "fear of missing out",
    "yolo": "you only live once",
    "irl": "in real life",
    "bff": "best friends forever",
}

airport_codes = {
    "JNB": "Johannesburg",
    "CAI": "Cairo",
    "LOS": "Lagos",
    "NBO": "Nairobi",
    "CPT": "Cape Town",
    "DUR": "Durban",
    "CMN": "Casablanca",
    "ADD": "Addis Ababa",
    "ALG": "Algiers",
    "ACC": "Accra",
    "SIN": "Singapore)",
    "HKG": "Hong Kong)",
    "PEK": "Beijing",
    "BKK": "Bangkok",
    "NRT": "Tokyo",
    "KUL": "Kuala Lumpur",
    "DEL": "New Delhi",
    "ICN": "Seoul",
    "CGK": "Jakarta",
    "PVG": "Shanghai",
    "MNL": "Manila",
    "DXB": "Dubai",
    "IST": "Istanbul",
    "SYD": "Sydney",
    "HND": "Tokyo",
    "CAN": "Guangzhou",
    "SVO": "Moscow",
    "TPE": "Taipei",
    "BOM": "Mumbai",
    "LHR": "London",
    "CDG": "Paris",
    "FRA": "Frankfurt",
    "AMS": "Amsterdam",
    "BCN": "Barcelona",
    "FCO": "Rome",
    "MAD": "Madrid",
    "MUC": "Munich",
    "ZRH": "Zurich",
    "CPH": "Copenhagen",
    "ATH": "Athens",
    "VIE": "Vienna",
    "ARN": "Stockholm",
    "WAW": "Warsaw",
    "OSL": "Oslo",
    "ATL": "Atlanta",
    "LAX": "Los Angeles",
    "ORD": "Chicago",
    "DFW": "Dallas",
    "DEN": "Denver",
    "JFK": "New York City",
    "SFO": "San Francisco",
    "LAS": "Las Vegas",
    "MIA": "Miami",
    "YYZ": "Toronto",
    "YVR": "Vancouver",
    "CUN": "Cancún",
    "MEX": "Mexico City",
    "PTY": "Panama City",
    "SJU": "San Juan",
    "HAV": "Havana",
    "GRU": "São Paulo",
    "EZE": "Buenos Aires",
    "BOG": "Bogotá",
    "SCL": "Santiago",
    "LIM": "Lima",
    "GIG": "Rio de Janeiro",
    "UIO": "Quito",
    "SJO": "San José",
    "ASU": "Asunción",
    "LAD": "Luanda",
    "MEL": "Melbourne",
    "BNE": "Brisbane",
    "AKL": "Auckland",
    "CHC": "Christchurch",
    "PER": "Perth",
    "ADL": "Adelaide",
    "HNL": "Honolulu",
    "NOU": "Nouméa",
    "PPT": "Papeete",
    "NAN": "Nadi",
    "GUM": "Guam)",
    "RAR": "Rarotonga",
    "APW": "Apia",
}

origin_loc_mapping = {
    "Abu Dhabi": "United Arab Emirates",
    "Acc": "Ghana",
    "Adampur": "India",
    "Addis Ababa": "Ethiopia",
    "Adelaide": "Australia",
    "Adl": "Australia",
    "Adélaïde": "Australia",
    "Afo": "Nigeria",
    "Agartala": "India",
    "Ahmadabad": "India",
    "Ahmedabad": "India",
    "Ajl": "India",
    "Ajmer": "India",
    "Akita": "Japan",
    "Akl": "New Zealand",
    "Algiers": "Algeria",
    "Amd": "India",
    "Amm": "Jordan",
    "Amman": "Jordan",
    "Amritsar": "India",
    "Ams": "Netherlands",
    "Amsterdam": "Netherlands",
    "An": "China",
    "Ankara": "Turkey",
    "Arn": "Sweden",
    "Ath": "Greece",
    "Athens": "Greece",
    "Atl": "United States",
    "Atlanta": "United States",
    "Atq": "India",
    "Auckland": "New Zealand",
    "Auh": "United Arab Emirates",
    "Aus": "Australia",
    "Bagdogra": "India",
    "Bah": "Bahrain",
    "Bahrain": "Bahrain",
    "Baku": "Azerbaijan",
    "Bali": "Indonesia",
    "Bali Denpasar": "Indonesia",
    "Banda Aceh": "Indonesia",
    "Bandar Lampung": "Indonesia",
    "Bandung": "Indonesia",
    "Bangalore": "India",
    "Bangkok": "Thailand",
    "Banjarmasin": "Indonesia",
    "Bankgok": "Thailand",
    "Bankok": "Thailand",
    "Baoshan": "China",
    "Barcelona": "Spain",
    "Batam": "Indonesia",
    "Bbi": "India",
    "Bbo": "Papua New Guinea",
    "Bcn": "Spain",
    "Bdj": "Indonesia",
    "Bdo": "Indonesia",
    "Beijing": "China",
    "Beirut": "Lebanon",
    "Belagavi": "India",
    "Belgaum": "India",
    "Belgrade": "Serbia",
    "Bengaluru": "India",
    "Bengkulu": "Indonesia",
    "Berau": "Indonesia",
    "Bergen": "Norway",
    "Berlin": "Germany",
    "Berlin Tegel": "Germany",
    "Bey": "Turkey",
    "Bhavnagar": "India",
    "Bhj": "India",
    "Bho": "India",
    "Bhopal": "India",
    "Bhubaneshwar": "India",
    "Bhubaneswar": "India",
    "Bhuj": "India",
    "Bhx": "United Kingdom",
    "Bikaner": "India",
    "Birmingham": "United Kingdom",
    "Bk": "Russia",
    "Bkk": "Thailand",
    "Blr": "India",
    "Bne": "Australia",
    "Bodrum": "Turkey",
    "Bologna": "Italy",
    "Bom": "India",
    "Bombay": "India",
    "Bos": "Bosnia and Herzegovina",
    "Brisbane": "Australia",
    "Brisibane": "Australia",
    "Bru": "Belgium",
    "Brussels": "Belgium",
    "Bruxelles": "Belgium",
    "Bucharest": "Romania",
    "Bud": "Hungary",
    "Budapest": "Hungary",
    "Buon Ma Thuat": "Vietnam",
    "Buon Ma Thuot": "Vietnam",
    "Busan": "South Korea",
    "Bxh": "China",
    "Cai": "Egypt",
    "Calcutta": "India",
    "Calicut": "India",
    "Cam Ranh": "Vietnam",
    "Can": "China",
    "Can Tho": "Vietnam",
    "Canberra": "Australia",
    "Cape": "South Africa",
    "Cardiff": "United Kingdom",
    "Casablanca": "Morocco",
    "Cbr": "Australia",
    "Ccj": "Thailand",
    "Ccu": "India",
    "Cdg": "France",
    "Cebu": "Philippines",
    "Cgk": "Indonesia",
    "Cgo": "China",
    "Cgq": "China",
    "Chandigargh": "India",
    "Chandigarh": "India",
    "Chandighar": "India",
    "Changchun": "China",
    "Changsha": "China",
    "Changzhou": "China",
    "Chc": "New Zealand",
    "Chengdu": "China",
    "Chennai": "India",
    "Chi": "China",
    "Chiang Mai": "Thailand",
    "Chiang Rai": "Thailand",
    "Chiangmai": "Thailand",
    "Chicago": "United States",
    "Chistchurch": "New Zealand",
    "Chongqing": "China",
    "Christchurch": "New Zealand",
    "Chu Lai": "Vietnam",
    "Ckg": "China",
    "Clark": "Philippines",
    "Cmb": "Sri Lanka",
    "Cmn": "Morocco",
    "Cms": "China",
    "Cnx": "Thailand",
    "Cochi": "India",
    "Cochin": "India",
    "Coimba": "India",
    "Cok": "India",
    "Colombo": "Sri Lanka",
    "Conakry": "Guinea",
    "Copenhagen": "Denmark",
    "Cph": "Denmark",
    "Cpt": "South Africa",
    "Crk": "Philippines",
    "Csx": "China",
    "Cts": "Japan",
    "Ctu": "China",
    "Cxr": "Vietnam",
    "Cz344": "China",
    "Cát Bi": "Vietnam",
    "Da Lat": "Vietnam",
    "Da Nang": "Vietnam",
    "Dac": "Bangladesh",
    "Dad": "Vietnam",
    "Dalat": "Vietnam",
    "Dalian": "China",
    "Dallas": "United States",
    "Dallas Fort Worth": "United States",
    "Dallas Ft Worth": "United States",
    "Dammam": "Saudi Arabia",
    "Danang": "Vietnam",
    "Dar Es Salaam": "Tanzania",
    "Dar Es Salam": "Tanzania",
    "Darbhanga": "India",
    "Davao": "Philippines",
    "Ded": "China",
    "Dehi": "India",
    "Dehli": "India",
    "Dehradun": "India",
    "Del": "India",
    "Delhi": "India",
    "Denpasar": "Indonesia",
    "Denpasar Bali": "Indonesia",
    "Det": "United States",
    "Dfw": "United States",
    "Dhaka": "Bangladesh",
    "Dharamsala": "India",
    "Dharamshala": "India",
    "Dibrugarh": "India",
    "Dimapur": "India",
    "Diqing": "China",
    "Dlc": "China",
    "Dme": "Russia",
    "Dmm": "Saudi Arabia",
    "Doh": "Qatar",
    "Doha": "Qatar",
    "Dps": "Indonesia",
    "Dub": "Ireland",
    "Dubai": "United Arab Emirates",
    "Dubai Dwc": "United Arab Emirates",
    "Dublin": "Ireland",
    "Dunhuang": "China",
    "Dur": "South Africa",
    "Durban": "South Africa",
    "Durgapur": "India",
    "Dus": "Germany",
    "Dusseldorf": "Germany",
    "Dwc": "United Arab Emirates",
    "Dxb": "United Arab Emirates",
    "Düsseldorf": "Germany",
    "Edi": "United Kingdom",
    "Edinburgh": "United Kingdom",
    "Edmon": "United States",
    "Entebbe": "Uganda",
    "Erbil": "Iraq",
    "Ewr": "United States",
    "Eze": "Argentina",
    "Fco": "Italy",
    "Fiji": "Fiji",
    "Foc": "China",
    "Fort Lauderdale": "United States",
    "Fra": "Germany",
    "Franfurt": "Germany",
    "Frankfurt": "Germany",
    "Ft Lauderdale": "United States",
    "Fuk": "Japan",
    "Fukuoka": "Japan",
    "Fuzhou": "China",
    "Gatwick": "United Kingdom",
    "Gau": "India",
    "Gauhati": "India",
    "Gay": "India",
    "Geneva": "Switzerland",
    "Gig": "Brazil",
    "Gla": "United Kingdom",
    "Glasgow": "United Kingdom",
    "Gmp": "South Korea",
    "Goa": "India",
    "Goi": "India",
    "Gorakhpur": "India",
    "Gothenburg": "Sweden",
    "Gru": "Brazil",
    "Guang Zhou": "China",
    "Guangdong": "China",
    "Guanghzou": "China",
    "Guangzhou": "China",
    "Guangzou": "China",
    "Guilin": "China",
    "Guiyang": "China",
    "Guwahat": "India",
    "Guwahati": "India",
    "Gva": "Switzerland",
    "Gwalior": "India",
    "Gyd": "Azerbaijan",
    "Hai Phong": "Vietnam",
    "Haikou": "China",
    "Hailaer": "China",
    "Hak": "China",
    "Ham": "Germany",
    "Hamburg": "Germany",
    "Han": "China",
    "Haneda": "Japan",
    "Hangzhou": "China",
    "Hanoi": "Vietnam",
    "Harbin": "China",
    "Hat Yao": "Thailand",
    "Hbe": "Egypt",
    "Hcmc": "Vietnam",
    "Heath": "United Kingdom",
    "Hefei": "China",
    "Heifei": "China",
    "Hel": "Finland",
    "Helsinki": "Finland",
    "Het": "China",
    "Hfe": "China",
    "Hgh": "China",
    "Hi": "China",
    "Hi Chi Minh": "Vietnam",
    "Hi Chi Minh City": "Vietnam",
    "Hkd": "China",
    "Hkg": "Hong Kong",
    "Hkt": "Thailand",
    "Hnd": "Japan",
    "Hnl": "United States",
    "Ho Chi Mihn City": "Vietnam",
    "Ho Chi Min City": "Vietnam",
    "Ho Chi Ming City": "Vietnam",
    "Ho Chi Minh": "Vietnam",
    "Ho Chi Minh City": "Vietnam",
    "Hohhot": "China",
    "Hong Hong": "Hong Kong",
    "Hong Kong": "Hong Kong",
    "Hongqiao": "China",
    "Honolulu": "United States",
    "Hous": "United States",
    "Hph": "India",
    "Hrb": "China",
    "Hubli": "India",
    "Hue": "Vietnam",
    "Hui": "China",
    "Huế": "Vietnam",
    "Hyd": "India",
    "Hyderabad": "India",
    "Iad": "United States",
    "Iah": "United States",
    "Icn": "South Korea",
    "Ika": "Iran",
    "Imphal": "India",
    "Incheon": "South Korea",
    "Indore": "India",
    "Irkutsk": "Russia",
    "Isb": "Pakistan",
    "Islamabad": "Pakistan",
    "Ist": "Turkey",
    "Istanbul": "Turkey",
    "Itami": "Japan",
    "Itm": "Japan",
    "Ixb": "India",
    "Ixc": "India",
    "Ixe": "India",
    "Ixg": "India",
    "Ixj": "India",
    "Ixm": "India",
    "Ixr": "India",
    "Ixz": "India",
    "Jabalpur": "India",
    "Jai": "India",
    "Jaipur": "India",
    "Jaisalmer": "India",
    "Jakarta": "Indonesia",
    "Jakatrta": "Indonesia",
    "Jambi": "Indonesia",
    "Jammu": "India",
    "Japan": "Japan",
    "Jayapura": "Indonesia",
    "Jed": "Saudi Arabia",
    "Jeddah": "Saudi Arabia",
    "Jeju": "South Korea",
    "Jeju Island": "South Korea",
    "Jfk": "United States",
    "Jfk New": "United States",
    "Jieyang": "China",
    "Jilin": "China",
    "Jinan": "China",
    "Jinghong": "China",
    "Jinnah Int": "Pakistan",
    "Jnb": "South Africa",
    "Jodhpur": "India",
    "Jogjakarta": "Indonesia",
    "Johannesbug": "South Africa",
    "Johannesburg": "South Africa",
    "Johannesburgh": "South Africa",
    "Kalaburagi": "India",
    "Kannur": "India",
    "Kanpur": "India",
    "Kansai": "Japan",
    "Kaohsiung": "Taiwan",
    "Karachi": "Pakistan",
    "Kathmandu": "Nepal",
    "Katmandu": "Nepal",
    "Kempegowda Bengaluru": "India",
    "Khar": "India",
    "Khi": "Pakistan",
    "Khn": "Thailand",
    "Khon Kaen": "Thailand",
    "Kiev": "Ukraine",
    "Kigali": "Rwanda",
    "Kix": "Japan",
    "Kmg": "China",
    "Kochi": "India",
    "Kochin": "India",
    "Kohnkaen": "Thailand",
    "Kolhapur": "India",
    "Kolkata": "India",
    "Kolkata (Ccu)": "India",
    "Kolkatta": "India",
    "Kota Kinabalu": "Malaysia",
    "Kozhikode": "India",
    "Kozikhode": "India",
    "Krabi": "Thailand",
    "Krakow": "Poland",
    "Ktm": "Nepal",
    "Kuala Lumpur": "Malaysia",
    "Kul": "Malaysia",
    "Kunming": "China",
    "Kupang": "Indonesia",
    "Kuwait": "Kuwait",
    "Kwe": "China",
    "Kwi": "Kuwait",
    "Kyiv": "Ukraine",
    "L": "China",
    "Labuan Bajo": "Indonesia",
    "Lagos": "Nigeria",
    "Lagos, Nigeria": "Nigeria",
    "Lahore": "Pakistan",
    "Langkawi": "Malaysia",
    "Larnaca": "Cyprus",
    "Las": "United States",
    "Las Vegas": "United States",
    "Lax": "United States",
    "Leh": "India",
    "Lgw": "United Kingdom",
    "Lhr": "United Kingdom",
    "Linyi": "China",
    "Lis": "Portugal",
    "Lisbon": "Portugal",
    "Lko": "India",
    "Lombok": "Indonesia",
    "London": "United Kingdom",
    "London Gatwick": "United Kingdom",
    "London Heah": "United Kingdom",
    "London Heath": "United Kingdom",
    "London Heatrhow": "United Kingdom",
    "London Stansted": "United Kingdom",
    "London, Uk": "United Kingdom",
    "Lop": "Unknown",
    "Los Angela": "Unknown",
    "Los Angeles": "United States",
    "Luanda": "Angola",
    "Lucknow": "India",
    "Lun": "Unknown",
    "Lusaka": "Zambia",
    "Luxor": "Egypt",
    "Lxa": "Unknown",
    "Maa": "Unknown",
    "Mad": "Unknown",
    "Madrid": "Spain",
    "Madurai": "India",
    "Mahe": "Unknown",
    "Mahé, Seychelles": "Seychelles",
    "Makassar": "Indonesia",
    "Malaga": "Spain",
    "Malang": "Indonesia",
    "Maldives": "Maldives",
    "Male": "Maldives",
    "Malta": "Malta",
    "Malé": "Maldives",
    "Man": "Côte d’Ivoire",
    "Manchester": "United Kingdom",
    "Mangalore": "India",
    "Mangaluru": "India",
    "Manila": "Philippines",
    "Mapu": "Unknown",
    "Marrakech": "Morocco",
    "Mauritius": "Mauritius",
    "Mco": "Unknown",
    "Mct": "Unknown",
    "Medan": "Indonesia",
    "Medina": "Saudi Arabia",
    "Meixian": "China",
    "Mel": "Unknown",
    "Melbourne": "Australia",
    "Mexico": "Mexico",
    "Mexico City": "Mexico",
    "Miami": "United States",
    "Mic": "Unknown",
    "Milan": "Italy",
    "Mle": "Unknown",
    "Mnl": "Unknown",
    "Mogadishu": "Somalia",
    "Montreal": "Canada",
    "Moscow": "Russia",
    "Mru": "Unknown",
    "Msp": "Unknown",
    "Muc": "Unknown",
    "Mumbai": "India",
    "Mumbai Parun": "Unknown",
    "Munich": "Germany",
    "Muscat": "Oman",
    "Mxp": "Unknown",
    "Mysore": "India",
    "München": "Germany",
    "Nagasaki": "Japan",
    "Nagoya": "Japan",
    "Nagpur": "India",
    "Naha": "Japan",
    "Nai": "Unknown",
    "Najaf": "Iraq",
    "Nanchang": "China",
    "Nanjing": "China",
    "Nanning": "China",
    "Narita": "Japan",
    "Narita,": "Unknown",
    "Nashik": "India",
    "Nbo": "Unknown",
    "Nce": "Unknown",
    "Ncl": "Unknown",
    "New": "Unknown",
    "New Chi": "Unknown",
    "New Dehli": "India",
    "New Delhi": "India",
    "Newark": "United States",
    "Newcastle": "United Kingdom",
    "Ngb": "Unknown",
    "Ngo": "Unknown",
    "Nha Trang": "Vietnam",
    "Nhat Trang": "Unknown",
    "Nhatrang": "Unknown",
    "Nias": "Unknown",
    "Nice": "France",
    "Ningbo": "China",
    "Nkg": "Unknown",
    "Nkm": "Unknown",
    "Nng": "Unknown",
    "Nny": "Unknown",
    "Nrt": "Unknown",
    "Nyc": "Unknown",
    "Odessa": "Ukraine",
    "Oka": "Unknown",
    "Okayama": "Japan",
    "Okinawa": "Japan",
    "Okinawa Naha": "Japan",
    "Ord": "Unknown",
    "Ordos": "China",
    "Orlando": "United States",
    "Osa": "Unknown",
    "Osaka": "Japan",
    "Osaka Itami": "Japan",
    "Osaka Kansai": "Japan",
    "Osl": "Unknown",
    "Oslo": "Norway",
    "Otp": "Unknown",
    "Panama": "Panama",
    "Pantnagar": "India",
    "Paris": "France",
    "Paris Cdg": "France",
    "Patna": "India",
    "Pdx": "Unknown",
    "Pek": "Unknown",
    "Pekanbaru": "Indonesia",
    "Pen": "Unknown",
    "Penang": "Malaysia",
    "Per": "Unknown",
    "Perth": "Australia",
    "Peshawar": "Pakistan",
    "Philadelphia": "United States",
    "Phl": "Unknown",
    "Phn": "Unknown",
    "Phnom Penh": "Cambodia",
    "Phu Quoc": "Vietnam",
    "Phuket": "Thailand",
    "Phuo Quoc": "Unknown",
    "Pisa": "Italy",
    "Pnh": "Unknown",
    "Pnq": "Unknown",
    "Pontianak": "Indonesia",
    "Port Blair": "India",
    "Portblair": "Unknown",
    "Pqc": "Unknown",
    "Prague": "Czech Republic",
    "Prg": "Unknown",
    "Psa": "Unknown",
    "Pune": "India",
    "Pvg": "Unknown",
    "Qingdao": "China",
    "Raipur": "India",
    "Rajkot": "India",
    "Ranchi": "India",
    "Ras Al Khaimah": "United Arab Emirates",
    "Rgn": "Unknown",
    "Riyadh": "Saudi Arabia",
    "Rpr": "Unknown",
    "Ruh": "Unknown",
    "S": "Unknown",
    "Sagwon": "Unknown",
    "Saigon": "Vietnam",
    "Saint": "Unknown",
    "Salalah": "Oman",
    "San": "Unknown",
    "San Diego": "United States",
    "San Francisco": "United States",
    "San Jose": "United States",
    "Sanfransico": "Unknown",
    "Santiago": "Chile",
    "Sanya": "China",
    "Sao": "Unknown",
    "Sao Paulo": "Brazil",
    "Sappo": "Unknown",
    "Sarajevo": "Bosnia and Herzegovina",
    "Sav": "Unknown",
    "Saw": "Unknown",
    "Sea": "Unknown",
    "Seattle": "United States",
    "Semarang": "Indonesia",
    "Seoul": "South Korea",
    "Seoul Gimpo": "South Korea",
    "Seoul Incheon": "South Korea",
    "Seychelles": "Seychelles",
    "Sfo": "United States",
    "Sgn": "Vietnam",
    "Sha": "China",
    "Shanghai": "China",
    "Shanghai Hongqiao": "China",
    "Shanghai Pudong": "China",
    "Sharjah": "United Arab Emirates",
    "She": "China",
    "Shenyang": "China",
    "Shenzen": "China",
    "Shenzhen": "China",
    "Shenzhen Bao'An": "China",
    "Shijiazhuang": "China",
    "Shirdi": "India",
    "Sibolga": "Indonesia",
    "Siem Reap": "Cambodia",
    "Silchar": "India",
    "Sin": "Singapore",
    "Singapore": "Singapore",
    "Singapore Changi": "Singapore",
    "Sjc": "United States",
    "Sjw": "China",
    "Sof": "Bulgaria",
    "Sofia": "Bulgaria",
    "Solo": "Indonesia",
    "Srinagar": "India",
    "St Petersburg": "Russia",
    "Stansted": "United Kingdom",
    "Sub": "Indonesia",
    "Sulaymaniyah": "Iraq",
    "Surabaya": "Indonesia",
    "Surat": "India",
    "Surat Thani": "Thailand",
    "Svo": "Russia",
    "Sxr": "India",
    "Syd": "Australia",
    "Sydney": "Australia",
    "Szx": "China",
    "São Paulo": "Brazil",
    "Taichung": "Taiwan",
    "Taif": "Saudi Arabia",
    "Taipei": "Taiwan",
    "Taiyuan": "China",
    "Tak": "Thailand",
    "Tan Son Nhat": "Vietnam",
    "Tao": "China",
    "Tbilisi": "Georgia",
    "Tblisi": "Georgia",
    "Tehran": "Iran",
    "Tel Aviv": "Israel",
    "Thailand": "Thailand",
    "Thanh Hoa": "Vietnam",
    "Thiruvananthapu": "India",
    "Thiruvananthapuram": "India",
    "Tianjin": "China",
    "Tif": "Saudi Arabia",
    "Tiruchirapalli": "India",
    "Tiruchirappalli": "India",
    "Tirupati": "India",
    "Tlv": "Israel",
    "Tna": "China",
    "Tpe": "Taiwan",
    "Trivandrum": "India",
    "Trivendrum": "India",
    "Tsn": "China",
    "Tu": "China",
    "Tulihal": "India",
    "Tun": "Tunisia",
    "Tunis": "Tunisia",
    "Tunisia": "Tunisia",
    "Turkey": "Turkey",
    "Tuticorin": "India",
    "Txl": "Germany",
    "Udaipur": "India",
    "Udon Thani": "Thailand",
    "Udr": "India",
    "Ujung Pandang": "Indonesia",
    "Ulaanbaatar": "Mongolia",
    "Uln": "Mongolia",
    "United States": "United States",
    "Urumchi": "China",
    "Urumqi": "China",
    "Usa": "United States",
    "Vadadora": "India",
    "Vadodara": "India",
    "Vancouver": "Canada",
    "Varanasi": "India",
    "Varansi": "India",
    "Vce": "Italy",
    "Venice": "Italy",
    "Vga": "India",
    "Vie": "Austria",
    "Vienna": "Austria",
    "Vientiane": "Laos",
    "Vijayawada": "India",
    "Vinh": "Vietnam",
    "Visakhapatnam": "India",
    "Vishakapatanam": "India",
    "Vishakapatnam": "India",
    "Vishakhapatnam": "India",
    "Vns": "India",
    "Vododhara": "India",
    "Vtz": "India",
    "Vyr": "Russia",
    "Warsaw": "Poland",
    "Washing": "United States",
    "Waw": "Poland",
    "Welling": "United Kingdom",
    "Wenzhou": "China",
    "Wlg": "New Zealand",
    "Wnz": "China",
    "Wuh": "China",
    "Wuhan": "China",
    "Wuz": "China",
    "Xi'An": "China",
    "Xi'Ning": "China",
    "Xiamen": "China",
    "Xian": "China",
    "Xining": "China",
    "Xiy": "China",
    "Xmn": "China",
    "Xnn": "China",
    "Xuzhou": "China",
    "Yahukimo": "Indonesia",
    "Yangon": "Myanmar",
    "Yangzhou": "China",
    "Yantai": "China",
    "Yinchuan": "China",
    "Yul": "Canada",
    "Yvr": "Canada",
    "Yyc": "Canada",
    "Yyz": "Canada",
    "Zag": "Croatia",
    "Zagreb": "Croatia",
    "Zanzibar": "Tanzania",
    "Zhanjiang": "China",
    "Zhegzhou": "China",
    "Zhengzhou": "China",
    "Zhuhai": "China",
    "Zrh": "Switzerland",
    "Zuh": "China",
    "Zurich": "Switzerland",
    "Zvartnots": "Armenia",
    "Zürich": "Switzerland",
    "{Vg": "Unknown",
    "Ürümqi": "China",
}


dest_loc_mapping = {
    "Abu Dhabi": "United Arab Emirates",
    "Abudhabi": "United Arab Emirates",
    "Abuja": "Nigeria",
    "Acc": "Ghana",
    "Add": "Ethiopia",
    "Addis Ababa": "Ethiopia",
    "Adelaide": "Australia",
    "Adl": "Australia",
    "Agartala": "India",
    "Ahemdabad": "India",
    "Ahmadabad": "India",
    "Ahmedabad": "India",
    "Aizwal": "India",
    "Ajl": "Unknown",
    "Ajmer": "India",
    "Akl": "New Zealand",
    "Alexandria": "Egypt",
    "Algiers": "Algeria",
    "Almaty": "Kazakhstan",
    "Amd": "India",
    "Amm": "Jordan",
    "Amman": "Jordan",
    "Amritsar": "India",
    "Ams": "Netherlands",
    "Amsterdam": "Netherlands",
    "Ankara": "Turkey",
    "Antalya": "Turkey",
    "Aomori": "Japan",
    "Arla": "Unknown",
    "Arn": "Sweden",
    "Atambua": "Indonesia",
    "Ath": "Greece",
    "Athens": "Greece",
    "Atl": "United States",
    "Atlanta": "United States",
    "Atq": "India",
    "Auckland": "New Zealand",
    "Auckland / Dubai": "New Zealand",
    "Aucklqnd": "New Zealand",
    "Auh": "United Arab Emirates",
    "Aurangabad": "India",
    "Australia": "Australia",
    "Bagdogra": "India",
    "Baghdogra": "India",
    "Bah": "Unknown",
    "Bahrain": "Bahrain",
    "Baku": "Azerbaijan",
    "Bali": "Indonesia",
    "Bandar Lampung": "Indonesia",
    "Bandar Seri Begawan": "Brunei",
    "Bangalore": "India",
    "Bangkok": "Thailand",
    "Bangkok Don Muang": "Thailand",
    "Banglore": "India",
    "Banjarmasin": "Indonesia",
    "Baoshan": "China",
    "Barcelona": "Spain",
    "Basra": "Iraq",
    "Batam": "Indonesia",
    "Bbi": "India",
    "Bcn": "Spain",
    "Bdj": "Indonesia",
    "Bdo": "Indonesia",
    "Bdq": "India",
    "Beg": "Serbia",
    "Begaluru": "India",
    "Beihai": "China",
    "Beijing": "China",
    "Beinjing": "China",
    "Beirut": "Lebanon",
    "Bejing": "China",
    "Belagaum": "India",
    "Belgrade": "Serbia",
    "Bengaluru": "India",
    "Bengaluru, India": "India",
    "Bengalurur": "India",
    "Bengkulu": "Indonesia",
    "Berau": "Indonesia",
    "Berlin": "Germany",
    "Bermuda": "Bermuda",
    "Bey": "Turkey",
    "Bhagdogra": "India",
    "Bho": "India",
    "Bhopal": "India",
    "Bhubabneswar": "India",
    "Bhubaneshwar": "India",
    "Bhubaneswar": "India",
    "Bhubneshwar": "India",
    "Bhx": "United Kingdom",
    "Bi": "India",
    "Birmingham": "United Kingdom",
    "Birmingham Uk": "United Kingdom",
    "Bishkek": "Kyrgyzstan",
    "Bkk": "Thailand",
    "Bkk Return": "Thailand",
    "Blq": "Italy",
    "Blr": "India",
    "Bne": "Australia",
    "Bom": "India",
    "Bombay": "India",
    "Bos": "United States",
    "Brisbane": "Australia",
    "Bru": "Belgium",
    "Brussels": "Belgium",
    "Bucharest": "Romania",
    "Budapest": "Hungary",
    "Busan": "South Korea",
    "C An": "Unknown",
    "Cai": "Egypt",
    "Cairns": "Australia",
    "Calgary": "Canada",
    "Calicut": "India",
    "Cam Ranh": "Vietnam",
    "Can": "China",
    "Can Tho": "Vietnam",
    "Canberra": "Australia",
    "Cardiff": "United Kingdom",
    "Casablanca": "Morocco",
    "Cbr": "Australia",
    "Ccu": "India",
    "Cdg": "France",
    "Cdg Pvg": "France",
    "Ceb": "Philippines",
    "Cebu": "Philippines",
    "Cgk": "Indonesia",
    "Cgo": "China",
    "Cgq": "China",
    "Chaing Mai": "Thailand",
    "Chandigarh": "India",
    "Changchun": "China",
    "Changsha": "China",
    "Changzhou": "China",
    "Chaoshan": "China",
    "Chc": "New Zealand",
    "Chenai": "India",
    "Chengdu": "China",
    "Chenna": "India",
    "Chennai": "India",
    "Chennai Return": "India",
    "Chiang Mai": "Thailand",
    "Chiang Rai": "Thailand",
    "Chicago": "United States",
    "Chicago O'Hare": "United States",
    "Chicago O'Hare (Ord)": "United States",
    "Chongqing": "China",
    "Christchurch": "New Zealand",
    "Chu Lai": "Vietnam",
    "Cjb": "India",
    "Cjicagpo": "Unknown",
    "Ckg": "China",
    "Ckholm": "Unknown",
    "Clark": "Philippines",
    "Cmb": "Sri Lanka",
    "Cmn": "Morocco",
    "Cnb": "India",
    "Cnx": "Thailand",
    "Cochi": "India",
    "Cochin": "India",
    "Coichin": "India",
    "Cok": "India",
    "Colombo": "Sri Lanka",
    "Copenhagen": "Denmark",
    "Cph": "Denmark",
    "Cpt": "South Africa",
    "Csx": "China",
    "Cts": "Japan",
    "Ctu": "China",
    "Cxr": "Vietnam",
    "Da Lat": "Vietnam",
    "Da Nang": "Vietnam",
    "Dac": "Bangladesh",
    "Dad": "Vietnam",
    "Dalat": "Vietnam",
    "Dalian": "China",
    "Dallas": "United States",
    "Dallas Fort Worth": "United States",
    "Dallas Ft Worth": "United States",
    "Dammam": "Saudi Arabia",
    "Danang": "Vietnam",
    "Dar": "Tanzania",
    "Dar Es Salaam": "Tanzania",
    "Darbhanga": "India",
    "Ded": "Unknown",
    "Dehradun": "India",
    "Dekhi": "Unknown",
    "Del": "India",
    "Delhi": "India",
    "Delhi Igi": "India",
    "Denpasar": "Indonesia",
    "Denpasar Bali": "Indonesia",
    "Densepar": "Unknown",
    "Dfw": "United States",
    "Dhaka": "Bangladesh",
    "Dharamshala": "India",
    "Dhm": "India",
    "Dibrugarh": "India",
    "Diha": "Unknown",
    "Diu": "India",
    "Dlc": "China",
    "Dme": "Russia",
    "Dmm": "Saudi Arabia",
    "Doh": "Qatar",
    "Doha": "Qatar",
    "Doha Airport": "Qatar",
    "Dong Hoi": "Vietnam",
    "Dongying": "China",
    "Dps": "Indonesia",
    "Dub": "Ireland",
    "Dubai": "United Arab Emirates",
    "Dubia": "Unknown",
    "Dublin": "Ireland",
    "Dulles": "United States",
    "Dur": "Unknown",
    "Durban": "South Africa",
    "Durgapur": "India",
    "Dus": "Germany",
    "Dushanbe": "Tajikistan",
    "Dusseldorf": "Germany",
    "Dwc": "United Arab Emirates",
    "Dxb": "United Arab Emirates",
    "Dyg": "Unknown",
    "Düsseldorf": "Germany",
    "Edi": "United Kingdom",
    "Edinburgh": "United Kingdom",
    "Entebbe": "Uganda",
    "Ewr": "United States",
    "Eze": "Argentina",
    "Faisalabad": "Pakistan",
    "Fco": "Italy",
    "Foc": "China",
    "Fra": "Germany",
    "Frankfurt": "Germany",
    "Frankfurt Vua Beijing": "Germany",
    "Fsz": "Unknown",
    "Fuk": "Japan",
    "Fukuoka": "Japan",
    "Fuzhou": "China",
    "Gatwick": "United Kingdom",
    "Gau": "India",
    "Geneva": "Switzerland",
    "Gimhae": "South Korea",
    "Gla": "United Kingdom",
    "Glasgow": "United Kingdom",
    "Goa": "India",
    "Goi": "India",
    "Gorakhpur": "India",
    "Gothenburg": "Sweden",
    "Gru": "Brazil",
    "Guangzhou": "China",
    "Guanhzhou": "China",
    "Guiyang": "China",
    "Guwahati": "India",
    "Guwhati": "India",
    "Gva": "Switzerland",
    "Gwalior": "India",
    "Gyakarta": "Indonesia",
    "Gyd": "Azerbaijan",
    "Ha Noi": "Vietnam",
    "Hai Phong": "Vietnam",
    "Haikou": "China",
    "Hak": "China",
    "Ham": "Germany",
    "Hamad": "Qatar",
    "Hamburg": "Germany",
    "Han": "China",
    "Haneda": "Japan",
    "Hangzhou": "China",
    "Hanoi": "Vietnam",
    "Hanoï": "Vietnam",
    "Harbin": "China",
    "Hat Yai": "Thailand",
    "Hav": "Cuba",
    "Hefei": "China",
    "Hel": "Finland",
    "Helsinki": "Finland",
    "Hfe": "China",
    "Hgh": "China",
    "Hi Chi Min City": "Vietnam",
    "Hi Chi Minh": "Vietnam",
    "Hi Chi Minh City": "Vietnam",
    "Hi Cho Minh": "Vietnam",
    "Hkd": "China",
    "Hkg": "Hong Kong",
    "Hkt": "Thailand",
    "Hnd": "Japan",
    "Hnl": "United States",
    "Ho Chi Mihh City": "Vietnam",
    "Ho Chi Min": "Vietnam",
    "Ho Chi Min City": "Vietnam",
    "Ho Chi Ming": "Vietnam",
    "Ho Chi Minh": "Vietnam",
    "Ho Chi Minh City": "Vietnam",
    "Ho Chi Minh Coty": "Vietnam",
    "Ho Cho Minh City": "Vietnam",
    "Hokkaido": "Japan",
    "Hong": "China",
    "Hong Hong": "China",
    "Hong Kong": "Hong Kong",
    "Honolulu": "United States",
    "Hrb": "China",
    "Hubli": "India",
    "Hue": "Vietnam",
    "Hui": "China",
    "Hyd": "India",
    "Hyderabad": "India",
    "Hydrabad": "India",
    "Hô Chi Minh": "Vietnam",
    "Iad": "United States",
    "Iah": "United States",
    "Icn": "South Korea",
    "Incheon": "South Korea",
    "Indire": "Unknown",
    "Indore": "India",
    "Isb": "Pakistan",
    "Isg": "Japan",
    "Ishigaki": "Japan",
    "Islamabad": "Pakistan",
    "Ist": "Turkey",
    "Istanbul": "Turkey",
    "Istanbul (Saw)": "Turkey",
    "Itm": "Japan",
    "Ixb": "India",
    "Ixc": "India",
    "Ixe": "India",
    "Ixg": "India",
    "Ixm": "India",
    "Ixz": "India",
    "Jabalpur": "India",
    "Jai": "India",
    "Jaipur": "India",
    "Jaisalmer": "India",
    "Jakarta": "Indonesia",
    "Jammu": "India",
    "Jayapura": "Indonesia",
    "Jdh": "India",
    "Jed": "Saudi Arabia",
    "Jeddah": "Saudi Arabia",
    "Jeju": "South Korea",
    "Jfk": "United States",
    "Jharsuguda": "India",
    "Jinan": "China",
    "Jiuzhaighou": "China",
    "Jnb": "South Africa",
    "Jodhpur": "India",
    "Jodphur": "India",
    "Jog": "Indonesia",
    "Johanesburg": "South Africa",
    "Johannesburg": "South Africa",
    "Jorhat": "India",
    "Jzh": "China",
    "Kabul": "Afghanistan",
    "Kannaur": "India",
    "Kannur": "India",
    "Kanpur": "India",
    "Kansa": "Unknown",
    "Kansai": "Japan",
    "Karachi": "Pakistan",
    "Kathmandu": "Nepal",
    "Keflavik": "Iceland",
    "Kempegowda": "India",
    "Kendari": "Indonesia",
    "Kerala": "India",
    "Khh": "Taiwan",
    "Khi": "Pakistan",
    "Khn": "China",
    "Kiev": "Ukraine",
    "Kigali": "Rwanda",
    "Kishangarh": "India",
    "Kix": "Japan",
    "Kmg": "China",
    "Kochi": "India",
    "Koh Samui": "Thailand",
    "Kolkata": "India",
    "Kolkota": "India",
    "Kota Kinabalu": "Malaysia",
    "Kozhikode": "India",
    "Krabi": "Thailand",
    "Ktm": "Nepal",
    "Kuala Lumper": "Malaysia",
    "Kuala Lumpur": "Malaysia",
    "Kuching": "Malaysia",
    "Kul": "Malaysia",
    "Kulu": "India",
    "Kunming": "China",
    "Kupang": "Indonesia",
    "Kuwait": "Kuwait",
    "Kwi": "Kuwait",
    "Kwl": "China",
    "Kyiv": "Ukraine",
    "La": "United States",
    "Labuan Bajo": "Indonesia",
    "Lagos": "Nigeria",
    "Lahore": "Pakistan",
    "Lahore Via \\Doha": "Pakistan",
    "Langkawi": "Malaysia",
    "Lanzhou": "China",
    "Larnaca": "Cyprus",
    "Las": "United States",
    "Lax": "United States",
    "Leh": "India",
    "Lgw": "United Kingdom",
    "Lhe": "Pakistan",
    "Lhr": "United Kingdom",
    "Lijiang": "China",
    "Lis": "Portugal",
    "Lisbon": "Portugal",
    "Lko": "India",
    "Lombok": "Indonesia",
    "London": "United Kingdom",
    "London Gatwick": "United Kingdom",
    "London Heathrw": "United Kingdom",
    "London Lhr": "United Kingdom",
    "Los": "Unknown",
    "Los Angeles": "United States",
    "Los Ángeles": "United States",
    "Lucknow": "India",
    "Luoyang": "China",
    "Lys": "France",
    "Maa": "India",
    "Mactan": "Philippines",
    "Mad": "Yemen",
    "Madrid": "Spain",
    "Madurai": "India",
    "Makassar": "Indonesia",
    "Maldives": "Maldives",
    "Male": "Maldives",
    "Malta": "Malta",
    "Malé": "Maldives",
    "Man": "Côte d'Ivoire",
    "Manado": "Indonesia",
    "Manchester": "United Kingdom",
    "Manchester Uk": "United Kingdom",
    "Mangalore": "India",
    "Mangaluru": "India",
    "Manila": "Philippines",
    "Mauritius": "Mauritius",
    "Mco": "United States",
    "Mct": "Oman",
    "Mdg": "Madagascar",
    "Me": "Unknown",
    "Medan": "Indonesia",
    "Medina": "Saudi Arabia",
    "Mel": "Australia",
    "Melbourne": "Australia",
    "Melbourne Australia": "Australia",
    "Mexico City": "Mexico",
    "Mfco": "Unknown",
    "Mfm": "Macau",
    "Mia": "United States",
    "Miami": "United States",
    "Milan": "Italy",
    "Mla": "Philippines",
    "Mle": "Maldives",
    "Mnl": "Philippines",
    "Montreal": "Canada",
    "Montréal": "Canada",
    "Moscow": "Russia",
    "Mru": "Mauritius",
    "Muc": "Germany",
    "Mudanjiang": "China",
    "Multan": "Pakistan",
    "Mum": "Unknown",
    "Mumbai": "India",
    "Mumbai (Bom)": "India",
    "Mumbai Return": "India",
    "Munich": "Germany",
    "Muscat": "Oman",
    "Mxp": "Italy",
    "Myj": "Japan",
    "N": "Unknown",
    "N Dc": "United States",
    "N Dulles": "United States",
    "Nadi": "Fiji",
    "Nag": "Japan",
    "Nagoya": "Japan",
    "Nagpur": "India",
    "Nah Trang": "Vietnam",
    "Naha": "Japan",
    "Najaf": "Iraq",
    "Nakhon Si Thammarat": "Thailand",
    "Nan": "Thailand",
    "Nanjing": "China",
    "Nanning": "China",
    "Narita": "Japan",
    "Nbo": "Kenya",
    "Nce": "France",
    "Ncl": "United Kingdom",
    "Nepal": "Nepal",
    "New Delhi": "India",
    "New Dheli": "India",
    "New Zealand": "New Zealand",
    "Newark": "United States",
    "Newcastle": "United Kingdom",
    "Ng": "Unknown",
    "Ngo": "Japan",
    "Ngs": "Japan",
    "Ngurah Rai": "Indonesia",
    "Ngyang": "China",
    "Nha Trang": "Vietnam",
    "Nice": "France",
    "Nkg": "China",
    "Nrt": "Japan",
    "Ntr": "Unknown",
    "Oit": "Japan",
    "Oka": "Japan",
    "Okinawa": "Japan",
    "Ord": "United States",
    "Orlando": "United States",
    "Osaka": "Japan",
    "Osaka (Itm)": "Japan",
    "Osaka Itami": "Japan",
    "Osaka Kansai": "Japan",
    "Osl": "Norway",
    "Oslo": "Norway",
    "Padang": "Indonesia",
    "Palangkarya": "Indonesia",
    "Paris": "France",
    "Paris Cdg": "France",
    "Patna": "India",
    "Pek": "China",
    "Penang": "Malaysia",
    "Per": "Unknown",
    "Perth": "Australia",
    "Philadelphia": "United States",
    "Phl": "United States",
    "Phnom Penh": "Cambodia",
    "Phu Quoc": "Vietnam",
    "Phuket": "Thailand",
    "Pleiku": "Vietnam",
    "Pleiku City": "Vietnam",
    "Pnh": "Cambodia",
    "Pnom Penh": "Cambodia",
    "Pnq": "India",
    "Pondicherry": "India",
    "Port Blair": "India",
    "Port Louis": "Mauritius",
    "Pqc": "Philippines",
    "Prague": "Czech Republic",
    "Prg": "Czech Republic",
    "Pty": "Panama",
    "Pune": "India",
    "Pune, India": "India",
    "Pus": "South Korea",
    "Pvg": "China",
    "Pvg Return": "China",
    "Qingdao": "China",
    "Qingdao Vua Shanghai": "China",
    "Qingdoa": "China",
    "Raipur": "India",
    "Rajahmundry": "India",
    "Rajkot": "India",
    "Ranchi": "India",
    "Re": "Unknown",
    "Rep": "Dominican Republic",
    "Rgn": "Myanmar",
    "Riyadh": "Saudi Arabia",
    "Rk": "Unknown",
    "Rk Jfk": "United States",
    "Saigon": "Vietnam",
    "Salalah": "Oman",
    "San": "United States",
    "San Diego": "United States",
    "San Francisco": "United States",
    "San Fransisco": "United States",
    "San Jose": "United States",
    "Sanya": "China",
    "Sao Paulo": "Brazil",
    "Sao Paulo Gru": "Brazil",
    "Sdyney": "Australia",
    "Se": "South Korea",
    "Sea": "United States",
    "Seattle": "United States",
    "Semarang": "Indonesia",
    "Seoul": "South Korea",
    "Seoul Gimpo": "South Korea",
    "Seoul Incheon": "South Korea",
    "Seychelles": "Seychelles",
    "Sfo": "United States",
    "Sgn": "Vietnam",
    "Sha": "China",
    "Shangai": "China",
    "Shanghai": "China",
    "Shanghai Hongqiao": "China",
    "Shanghai Pudong": "China",
    "Sharjah": "United Arab Emirates",
    "She": "China",
    "Shenyang": "China",
    "Shenzen": "China",
    "Shenzhen": "China",
    "Shirdi": "India",
    "Sialkot": "Pakistan",
    "Siem Reap": "Cambodia",
    "Silchar": "India",
    "Sin": "Singapore",
    "Singapore": "Singapore",
    "Singapore Return": "Singapore",
    "Singaporec": "Singapore",
    "Singaporw": "Singapore",
    "Singapour": "Singapore",
    "Sjc": "United States",
    "Sjw": "China",
    "Sng": "Singapore",
    "Sof": "Bulgaria",
    "Sofia": "Bulgaria",
    "Soul": "South Korea",
    "Srinagar": "India",
    "Srinagar (Kashmir)": "India",
    "St Petersburg": "Russia",
    "St.Petersburg": "Russia",
    "Stansted": "United Kingdom",
    "Std": "India",
    "Sub": "Indonesia",
    "Sulaymaniyah": "Iraq",
    "Surabaya": "Indonesia",
    "Surat": "India",
    "Surat Thani": "Thailand",
    "Svo": "Russia",
    "Syd": "Australia",
    "Sydney": "Australia",
    "Syz": "Syria",
    "Szx": "China",
    "São Paulo": "Brazil",
    "Taif": "Saudi Arabia",
    "Tainan": "Taiwan",
    "Taipei": "Taiwan",
    "Taiyuan": "China",
    "Tallinn": "Estonia",
    "Tan Son Nhat": "Vietnam",
    "Tao": "China",
    "Tarakan": "Indonesia",
    "Tas": "Turkey",
    "Tashkent": "Uzbekistan",
    "Tbilisi": "Georgia",
    "Tblisi": "Georgia",
    "Tehran": "Iran",
    "Tel Aviv": "Israel",
    "Thailand": "Thailand",
    "Thanh Hoa": "Vietnam",
    "Thiruvananthapuram": "India",
    "Thiruvananthapuran": "India",
    "Tianjin": "China",
    "Tirupati": "India",
    "Tkg": "Indonesia",
    "Tna": "China",
    "Tpe": "Taiwan",
    "Trichy": "India",
    "Trivandrum": "India",
    "Trv": "India",
    "Tsn": "China",
    "Tunis": "Tunisia",
    "Txl": "Germany",
    "Udaipur": "India",
    "Udon Thani": "Thailand",
    "Udr": "India",
    "Ulaanbaatar": "Mongolia",
    "Ulaanbaatar (Mongolia)": "Mongolia",
    "Uln": "Mongolia",
    "Um": "China",
    "Urumqi": "China",
    "Usm": "Thailand",
    "Vadodara": "India",
    "Vancouver": "Canada",
    "Varanasi": "India",
    "Vca": "Vietnam",
    "Vce": "Italy",
    "Venice": "Italy",
    "Vie": "Austria",
    "Vienna": "Austria",
    "Vientiane": "Laos",
    "Vijayawada": "India",
    "Vinh City": "Vietnam",
    "Visakhapatnam": "India",
    "Vns": "India",
    "Vtz": "India",
    "W": "China",
    "Warsaw": "Poland",
    "Waw": "Poland",
    "Wenzhou": "China",
    "Wien": "Austria",
    "Windhoek": "Namibia",
    "Winnipeg": "Canada",
    "Wn": "China",
    "Wnz": "China",
    "Wuh": "China",
    "Wuhan": "China",
    "Wux": "China",
    "Wuxi": "China",
    "Xi'An": "China",
    "Xiamen": "China",
    "Xian": "China",
    "Xining": "China",
    "Xiy": "China",
    "Yangon": "Myanmar",
    "Yangzhou": "China",
    "Yerevan": "Armenia",
    "Yinchuan": "China",
    "Yul": "Canada",
    "Yuncheng": "China",
    "Yvr": "Canada",
    "Yyc": "Canada",
    "Yyz": "Canada",
    "Zagreb": "Croatia",
    "Zanzibar": "Tanzania",
    "Zha": "China",
    "Zhengzhou": "China",
    "Zhuhai": "China",
    "Zrh": "Switzerland",
    "Zuh": "China",
    "Zuhai": "China",
    "Zurich": "Switzerland",
    "Zürich": "Switzerland",
}
