contraction_mapping = {
    "ain't": "is not",
    "aren't": "are not",
    "can't": "cannot",
    "'cause": "because",
    "could've": "could have",
    "couldn't": "could not",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "hadn't": "had not",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he would",
    "he'll": "he will",
    "he's": "he is",
    "how'd": "how did",
    "how'd'y": "how do you",
    "how'll": "how will",
    "how's": "how is",
    "I'd": "I would",
    "I'd've": "I would have",
    "I'll": "I will",
    "I'll've": "I will have",
    "I'm": "I am",
    "I've": "I have",
    "i'd": "i would",
    "i'd've": "i would have",
    "i'll": "i will",
    "i'll've": "i will have",
    "i'm": "i am",
    "i've": "i have",
    "isn't": "is not",
    "it'd": "it would",
    "it'd've": "it would have",
    "it'll": "it will",
    "it'll've": "it will have",
    "it's": "it is",
    "let's": "let us",
    "ma'am": "madam",
    "mayn't": "may not",
    "might've": "might have",
    "mightn't": "might not",
    "mightn't've": "might not have",
    "must've": "must have",
    "mustn't": "must not",
    "mustn't've": "must not have",
    "needn't": "need not",
    "needn't've": "need not have",
    "o'clock": "of the clock",
    "oughtn't": "ought not",
    "oughtn't've": "ought not have",
    "shan't": "shall not",
    "sha'n't": "shall not",
    "shan't've": "shall not have",
    "she'd": "she would",
    "she'd've": "she would have",
    "she'll": "she will",
    "she'll've": "she will have",
    "she's": "she is",
    "should've": "should have",
    "shouldn't": "should not",
    "shouldn't've": "should not have",
    "so've": "so have",
    "so's": "so as",
    "this's": "this is",
    "that'd": "that would",
    "that'd've": "that would have",
    "that's": "that is",
    "there'd": "there would",
    "there'd've": "there would have",
    "there's": "there is",
    "here's": "here is",
    "they'd": "they would",
    "they'd've": "they would have",
    "they'll": "they will",
    "they'll've": "they will have",
    "they're": "they are",
    "they've": "they have",
    "to've": "to have",
    "wasn't": "was not",
    "we'd": "we would",
    "we'd've": "we would have",
    "we'll": "we will",
    "we'll've": "we will have",
    "we're": "we are",
    "we've": "we have",
    "weren't": "were not",
    "what'll": "what will",
    "what'll've": "what will have",
    "what're": "what are",
    "what's": "what is",
    "what've": "what have",
    "when's": "when is",
    "when've": "when have",
    "where'd": "where did",
    "where's": "where is",
    "where've": "where have",
    "who'll": "who will",
    "who'll've": "who will have",
    "who's": "who is",
    "who've": "who have",
    "why's": "why is",
    "why've": "why have",
    "will've": "will have",
    "won't": "will not",
    "won't've": "will not have",
    "would've": "would have",
    "wouldn't": "would not",
    "wouldn't've": "would not have",
    "y'all": "you all",
    "y'all'd": "you all would",
    "y'all'd've": "you all would have",
    "y'all're": "you all are",
    "y'all've": "you all have",
    "you'd": "you would",
    "you'd've": "you would have",
    "you'll": "you will",
    "you'll've": "you will have",
    "you're": "you are",
    "you've": "you have",
    "ws": "was",
    "w": "with",
    "msg": "message",
    "ms": "miss",
    "u": "you",
    "ur": "your",
    "r": "are",
    "b": "be",
    "d": "the",
    "n": "and",
    "k": "ok",
    "kk": "ok",
    "missin": "missing",
    "mr": "mister",
    "mrs": "misses",
    "ms.": "miss",
}


chat_words_replacements = {
    # Common Chat Words
    "np": "no problem",
    "tho": "though",
    "cuz": "because",
    "gonna": "going to",
    "wanna": "want to",
    "gotta": "got to",
    "kinda": "kind of",
    "sorta": "sort of",
    "lemme": "let me",
    "gimme": "give me",
    "ain't": "am not/is not/are not",
    "wth": "what the hell",
    "omfg": "oh my fucking god",
    "gtg": "got to go",
    "ttyl": "talk to you later",
    "afaik": "as far as I know",
    "bday": "birthday",
    # Review related Words
    "awesome": "extremely good",
    "amazing": "astonishing",
    "awful": "terrible",
    "terrible": "horrible",
    "excellent": "outstanding",
    "fantastic": "extraordinary",
    "brilliant": "superb",
    "horrendous": "dreadful",
    "magnificent": "splendid",
    "phenomenal": "remarkable",
    "subpar": "below average",
    "mediocre": "average",
    "impressive": "striking",
    "disappointing": "unsatisfying",
    "satisfactory": "adequate",
    "stellar": "exceptional",
    "flawless": "perfect",
    "overrated": "overestimated",
    "underrated": "underestimated",
    # Expressions
    "btw": "by the way",
    "fyi": "for your information",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "lol": "laughing out loud",
    "rofl": "rolling on the floor laughing",
    "omg": "oh my god",
    "omfg": "oh my fucking god",
    "wtf": "what the fuck",
    "gtfo": "get the fuck out",
    "fomo": "fear of missing out",
    "yolo": "you only live once",
    "irl": "in real life",
    "bff": "best friends forever",
}

airport_codes = {
    "JNB": "Johannesburg",
    "CAI": "Cairo",
    "LOS": "Lagos",
    "NBO": "Nairobi",
    "CPT": "Cape Town",
    "DUR": "Durban",
    "CMN": "Casablanca",
    "ADD": "Addis Ababa",
    "ALG": "Algiers",
    "ACC": "Accra",
    "SIN": "Singapore)",
    "HKG": "Hong Kong)",
    "PEK": "Beijing",
    "BKK": "Bangkok",
    "NRT": "Tokyo",
    "KUL": "Kuala Lumpur",
    "DEL": "New Delhi",
    "ICN": "Seoul",
    "CGK": "Jakarta",
    "PVG": "Shanghai",
    "MNL": "Manila",
    "DXB": "Dubai",
    "IST": "Istanbul",
    "SYD": "Sydney",
    "HND": "Tokyo",
    "CAN": "Guangzhou",
    "SVO": "Moscow",
    "TPE": "Taipei",
    "BOM": "Mumbai",
    "LHR": "London",
    "CDG": "Paris",
    "FRA": "Frankfurt",
    "AMS": "Amsterdam",
    "BCN": "Barcelona",
    "FCO": "Rome",
    "MAD": "Madrid",
    "MUC": "Munich",
    "ZRH": "Zurich",
    "CPH": "Copenhagen",
    "ATH": "Athens",
    "VIE": "Vienna",
    "ARN": "Stockholm",
    "WAW": "Warsaw",
    "OSL": "Oslo",
    "ATL": "Atlanta",
    "LAX": "Los Angeles",
    "ORD": "Chicago",
    "DFW": "Dallas",
    "DEN": "Denver",
    "JFK": "New York City",
    "SFO": "San Francisco",
    "LAS": "Las Vegas",
    "MIA": "Miami",
    "YYZ": "Toronto",
    "YVR": "Vancouver",
    "CUN": "Cancún",
    "MEX": "Mexico City",
    "PTY": "Panama City",
    "SJU": "San Juan",
    "HAV": "Havana",
    "GRU": "São Paulo",
    "EZE": "Buenos Aires",
    "BOG": "Bogotá",
    "SCL": "Santiago",
    "LIM": "Lima",
    "GIG": "Rio de Janeiro",
    "UIO": "Quito",
    "SJO": "San José",
    "ASU": "Asunción",
    "LAD": "Luanda",
    "MEL": "Melbourne",
    "BNE": "Brisbane",
    "AKL": "Auckland",
    "CHC": "Christchurch",
    "PER": "Perth",
    "ADL": "Adelaide",
    "HNL": "Honolulu",
    "NOU": "Nouméa",
    "PPT": "Papeete",
    "NAN": "Nadi",
    "GUM": "Guam)",
    "RAR": "Rarotonga",
    "APW": "Apia",
}


origin_maps = mapping = {
    'Lhr': 'London',
    'Pek': 'Beijing',
    'Lax': 'Los Angeles',
    'S': 'Stockholm',
    '': 'Unknown',
    'Syd': 'Sydney',
    'Hkg': 'Hong Kong',
    'Fra': 'Frankfurt',
    'Yul': 'Montreal',
    'Sfo': 'San Francisco',
    'Jfk': 'New York City',
    'Mel': 'Melbourne',
    '{vg': 'Virgin Gorda',
    'Pvg': 'Shanghai',
    'Nrt': 'Tokyo',
    'Bkk': 'Bangkok',
    'Mnl': 'Manila',
    'Hel': 'Helsinki',
    'Isb': 'Islamabad',
    'Yvr': 'Vancouver',
    'Yyc': 'Calgary',
    'Hnd': 'Tokyo',
    'Vie': 'Vienna',
    'Akl': 'Auckland',
    'Icn': 'Incheon',
    'Can': 'Guangzhou',
    'Sgn': 'Ho Chi Minh City',
    'Ctu': 'Chengdu',
    'Del': 'Delhi',
    'Dus': 'Düsseldorf',
    'Bud': 'Budapest',
    'Iah': 'Houston',
    'Ewr': 'Newark',
    'Sha': 'Shanghai',
    'Kul': 'Kuala Lumpur',
    'Fco': 'Rome',
    'Hkt': 'Phuket',
    'Cdg': 'Paris',
    'Sin': 'Singapore',
    'Hgh': 'Hangzhou',
    'Nkm': 'Nagoya',
    'Cph': 'Copenhagen',
    'Uln': 'Ulaanbaatar',
    'Bcn': 'Barcelona',
    'Gmp': 'Seoul',
    'Hrb': 'Harbin',
    'Hnl': 'Honolulu',
    'Tpe': 'Taipei',
    'Xiy': "Xi'an",
    'Khn': 'Nanchang',
    'Iad': 'Washington, D.C.',
    'New': 'New Orleans',
    'Bom': 'Mumbai',
    'Ord': 'Chicago',
    'Bhx': 'Birmingham',
    'Lko': 'Lucknow',
    'Rgn': 'Yangon',
    'Ccu': 'Kolkata',
    'Ruh': 'Riyadh',
    'Maa': 'Chennai',
    'Hyd': 'Hyderabad',
    'Goi': 'Goa',
    'Dxb': 'Dubai',
    'Udr': 'Udaipur',
    'Bxh': 'Balkhash',
    'Cms': 'Scusciuban',
    'Vns': 'Varanasi',
    'Amd': 'Ahmedabad',
    'Ixb': 'Bagdogra',
    'Bho': 'Bhopal',
    'Ktm': 'Kathmandu',
    'Ixc': 'Chandigarh',
    'Bbi': 'Bhubaneswar',
    'Mxp': 'Milan',
    'Gay': 'Gaya',
    'Goa': 'Genoa',
    'Leh': 'Leh',
    'Ccj': 'Kozhikode',
    'Jai': 'Jaipur',
    'Vtz': 'Visakhapatnam',
    'Blr': 'Bangalore',
    'Sjc': 'San Jose',
    'Cgk': 'Jakarta',
    'Osa': 'Osaka',
    'Fuk': 'Fukuoka',
    'Bru': 'Brussels',
    'Xmn': 'Xiamen',
    'Sea': 'Seattle',
    'Itm': 'Osaka',
    'Kix': 'Osaka',
    'Aus': 'Austin',
    'Tak': 'Takamatsu',
    'Vce': 'Venice',
    'Usa': 'Concord',
    'Hi': 'Unknown',
    'Cmb': 'Colombo',
    'Szx': 'Shenzhen',
    'Yyz': 'Toronto',
    'Cgq': 'Changchun',
    'Pnh': 'Phnom Penh',
    'Nkg': 'Nanjing',
    'Ams': 'Amsterdam',
    'Wuz': 'Wuzhou',
    'Oka': 'Okinawa',
    'Dps': 'Denpasar',
    'Prg': 'Prague',
    'Ckg': 'Chongqing',
    'Xnn': 'Xining',
    'Mru': 'Mauritius',
    'Per': 'Perth',
    'Nng': 'Nanning',
    'Tna': 'Jinan',
    'She': 'Shenyang',
    'Bne': 'Brisbane',
    'Lxa': 'Lhasa',
    'Hak': 'Haikou',
    'Tsn': 'Tianjin',
    'Foc': 'Fuzhou',
    'Svo': 'Moscow',
    'Nbo': 'Nairobi',
    'An': 'Unknown',
    'Phn': 'Port Huron',
    'Sjw': 'Shijiazhuang',
    'Het': 'Hohhot',
    'Zuh': 'Zhuhai',
    'Cnx': 'Chiang Mai',
    'Hfe': 'Hefei',
    'Vyr': 'Vancouver',
    'Cgo': 'Zhengzhou',
    'Kmg': 'Kunming',
    'Csx': 'Changsha',
    'Tao': 'Qingdao',
    'Ngb': 'Ningbo',
    'Wuh': 'Wuhan',
    'Nny': 'Nanyang',
    'Chc': 'Christchurch',
    'Pqc': 'Phu Quoc Island',
    'Wnz': 'Wenzhou',
    'Dlc': 'Dalian',
    'Afo': 'Afton',
    'Kwe': 'Guiyang',
    'Nai': 'Annai',
    'Cai': 'Cairo',
    'Nce': 'Nice',
    'Bos': 'Boston',
    'Arn': 'Stockholm',
    'Jnb': 'Johannesburg',
    'Adl': 'Adelaide',
    'Bah': 'Bahrain',
    'Doh': 'Doha',
    'Cpt': 'Cape Town',
    'Nyc': 'New York City',
    'Lgw': 'London',
    'Gva': 'Geneva',
    'Gla': 'Glasgow',
    'Dfw': 'Dallas',
    'Mco': 'Orlando',
    'Lis': 'Lisbon',
    'Dur': 'Durban',
    'Ncl': 'Newcastle',
    'Man': 'Manchester',
    'Khi': 'Karachi',
    'Lun': 'Lusaka',
    'Acc': 'Accra',
    'Muc': 'Munich',
    'Mad': 'Madrid',
    'Ham': 'Hamburg',
    'Kwi': 'Kuwait City',
    'Ist': 'Istanbul',
    'Cmn': 'Casablanca',
    'Mct': 'Muscat',
    'Osl': 'Oslo',
    'Dmm': 'Dammam',
    'Zrh': 'Zurich',
    'Dub': 'Dublin',
    'Eze': 'Buenos Aires',
    'Jed': 'Jeddah',
    'Gig': 'Rio de Janeiro',
    'Mle': 'Male',
    'Waw': 'Warsaw',
    'Ath': 'Athens',
    'Otp': 'Bucharest',
    'Sav': 'Savannah',
    'L': 'Unknown',
    'Det': 'Detroit',
    'Pnq': 'Pune',
    'Cok': 'Kochi',
    'Ixj': 'Jammu',
    'Ixr': 'Ranchi',
    'Tu': 'Tucson',
    'San': 'San Diego',
    'Han': 'Hanoi',
    'Hkd': 'Hakodate',
    'Cts': 'Sapporo',
    'Chi': 'Chicago',
    'Bhj': 'Bhuj',
    'Auh': 'Abu Dhabi',
    'Ajl': 'Aizawl',
    'Rpr': 'Raipur',
    'Msp': 'Minneapolis',
    'Pdx': 'Portland',
    'Tlv': 'Tel Aviv',
    'Ngo': 'Nagoya',
    'Gru': 'Sao Paulo',
    'Sub': 'Surabaya',
    'Lop': 'Praya',
    'Bdo': 'Bandung',
    'Bdj': 'Banjarmasin',
    'Tif': 'Taif',
    'Crk': 'Angeles City',
    'Edi': 'Edinburgh',
    'Phl': 'Philadelphia',
    'Dwc': 'Dubai',
    'Txl': 'Berlin',
    'Saw': 'Istanbul',
    'Bey': 'Beirut',
    'Gyd': 'Ganja',
    'Hbe': 'Hefei',
    'Amm': 'Amman',
    'Pen': 'Penang',
    'Psa': 'Pisa',
    'Zag': 'Zagreb',
    'Sao': 'São Paulo',
    'Sof': 'Sofia',
    'Las': 'Las Vegas',
    'Ika': 'Tehran',
    'Atl': 'Atlanta',
    'Tun': 'Tunis',
    'Mic': 'Minneapolis',
    'Dac': 'Dhaka',
    'Wlg': 'Wellington',
    'Cbr': 'Canberra',
    'Bk': 'Bengkulu',
    'Dme': 'Moscow',
    'Atq': 'Amritsar',
    'Ixz': 'Port Blair',
    'Ded': 'Dehradun',
    'Ixe': 'Mangalore',
    'Ixg': 'Belgaum',
    'Vga': 'Vijayawada',
    'Ixm': 'Port Blair',
    'Dad': 'Da Nang',
    'Hui': 'Hue',
    'Cxr': 'Nha Trang',
    'Hph': 'Haiphong',
    'Hue': 'Hue',
    'Hue': 'Hue',
    'Bbo': 'Berbera',
    'Gau': 'Guwahati',
    'Sxr': 'Srinagar'
}

destination_mapping = {
    'Hnd': 'Tokyo',
    'Sfo': 'San Francisco',
    'N': 'Unknown',
    'Jfk': 'New York',
    'Tpe': 'Taipei',
    'Hkg': 'Hong Kong',
    'Ctu': 'Chengdu',
    'Tsn': 'Tianjin',
    'Rk': 'Rock Springs',
    'Xiy': "Xi'an",
    'Bkk': 'Bangkok',
    'Hrb': 'Harbin',
    'Mfm': 'Macau',
    'Mel': 'Melbourne',
    'Fco': 'Rome',
    'Fra': 'Frankfurt',
    'Can': 'Guangzhou',
    'Lhr': 'London',
    'Lax': 'Los Angeles',
    'Syd': 'Sydney',
    'Hgh': 'Hangzhou',
    'Hkt': 'Phuket',
    'Muc': 'Munich',
    'Sgn': 'Ho Chi Minh City',
    'Pek': 'Beijing',
    'Mnl': 'Manila',
    'Cgq': 'Changchun',
    'Icn': 'Seoul',
    'Del': 'Delhi',
    'Nrt': 'Tokyo',
    'Bom': 'Mumbai',
    'Sha': 'Shanghai',
    'Bcn': 'Barcelona',
    'Sin': 'Singapore',
    'Kix': 'Osaka',
    'Yvr': 'Vancouver',
    'Cdg': 'Paris',
    'Szx': 'Shenzhen',
    'Akl': 'Auckland',
    'Cnx': 'Chiang Mai',
    'Vie': 'Vienna',
    'Iad': 'Washington, D.C.',
    'Uln': 'Ulaanbaatar',
    'Gva': 'Geneva',
    'Svo': 'Moscow',
    'Iah': 'Houston',
    'Hav': 'Havana',
    'Arn': 'Stockholm',
    'Khn': 'Nanchang',
    'Ngo': 'Nagoya',
    'Ewr': 'Newark',
    'Ckg': 'Chongqing',
    'Pvg': 'Shanghai',
    'Kwl': 'Guilin',
    'Wnz': 'Wenzhou',
    'Cgk': 'Jakarta',
    'Tao': 'Qingdao',
    'Dus': 'Düsseldorf',
    'Yul': 'Montreal',
    '': 'Unknown',
    'Me': 'Medan',
    'Ng': 'Nagasaki',
    'Leh': 'Leh',
    'Goi': 'Goa',
    'Hyd': 'Hyderabad',
    'W': 'Unknown',
    'Ccu': 'Kolkata',
    'Dxb': 'Dubai',
    'Blr': 'Bengaluru',
    'Jdh': 'Jodhpur',
    'Nag': 'Nagpur',
    'Cok': 'Kochi',
    'Atq': 'Amritsar',
    'Maa': 'Chennai',
    'Ord': 'Chicago',
    'Auh': 'Abu Dhabi',
    'Bbi': 'Bhubaneswar',
    'Cjb': 'Coimbatore',
    'Ajl': 'Aizawl',
    'Lko': 'Lucknow',
    'Bdq': 'Vadodara',
    'Vns': 'Varanasi',
    'Amd': 'Ahmedabad',
    'Goa': 'Goa',
    'Diu': 'Diu',
    'Bi': 'Bismarck',
    'Pnq': 'Pune',
    'Gau': 'Guwahati',
    'Jai': 'Jaipur',
    'Itm': 'Osaka',
    'Hkd': 'Hakodate',
    'Isg': 'Ishigaki',
    'Dlc': 'Dalian',
    'Ngs': 'Nagasaki',
    'Myj': 'Matsuyama',
    'Sjc': 'San Jose',
    'Oka': 'Okinawa',
    'Kul': 'Kuala Lumpur',
    'She': 'Shenyang',
    'Hnl': 'Honolulu',
    'Jzh': 'Jiuzhaigou',
    'Kmg': 'Kunming',
    'Pus': 'Busan',
    'Wuh': 'Wuhan',
    'Yyz': 'Toronto',
    'Nkg': 'Nanjing',
    'Pnh': 'Phnom Penh',
    'Ams': 'Amsterdam',
    'Fsz': 'Shizuoka',
    'Hfe': 'Hefei',
    'Dyg': 'Zhangjiajie',
    'Zuh': 'Zhuhai',
    'Rep': 'Punta Cana',
    'Wux': 'Wuxi',
    'La': 'Los Angeles',
    'Cgo': 'Zhengzhou',
    'Dps': 'Denpasar',
    'Bne': 'Brisbane',
    'Ktm': 'Kathmandu',
    'Per': 'Perth',
    'Tna': 'Jinan',
    'Foc': 'Fuzhou',
    'Hak': 'Haikou',
    'Sjw': 'Shijiazhuang',
    'Csx': 'Changsha',
    'Nbo': 'Nairobi',
    'Chc': 'Christchurch',
    'Zha': 'Zhanjiang',
    'Cxr': 'Nha Trang',
    'Mdg': 'Mudanjiang',
    'Yyc': 'Calgary',
    'Adl': 'Adelaide',
    'Dmm': 'Dammam',
    'Waw': 'Warsaw',
    'Bhx': 'Birmingham',
    'Cpt': 'Cape Town',
    'Wn': 'Winnipeg',
    'Dme': 'Moscow',
    'Lgw': 'London',
    'Vce': 'Venice',
    'Man': 'Manchester',
    'Std': 'Santo Domingo',
    'Kwi': 'Kuwait City',
    'Khi': 'Karachi',
    'Add': 'Addis Ababa',
    'Mxp': 'Milan',
    'Doh': 'Doha',
    'Lhe': 'Lahore',
    'Jnb': 'Johannesburg',
    'Bos': 'Boston',
    'Mru': 'Mauritius',
    'Dar': 'Dar es Salaam',
    'Cmb': 'Colombo',
    'Jed': 'Jeddah',
    'Cph': 'Copenhagen',
    'Ncl': 'Newcastle',
    'Gla': 'Glasgow',
    'Sea': 'Seattle',
    'Mct': 'Muscat',
    'Pty': 'Panama City',
    'Dub': 'Dublin',
    'Bru': 'Brussels',
    'Acc': 'Accra',
    'Mle': 'Malé',
    'Zrh': 'Zurich',
    'Dac': 'Dhaka',
    'Trv': 'Thiruvananthapuram',
    'Mad': 'Madrid',
    'Lis': 'Lisbon',
    'Cmn': 'Casablanca',
    'Prg': 'Prague',
    'Mla': 'Kuala Lumpur',
    'Eze': 'Buenos Aires',
    'Ham': 'Hamburg',
    'Nce': 'Nice',
    'Bey': 'Beirut',
    'Ath': 'Athens',
    'Gru': 'São Paulo',
    'Amm': 'Amman',
    'Dur': 'Durban',
    'Cai': 'Cairo',
    'Ceb': 'Cebu',
    'Blq': 'Bologna',
    'Isb': 'Islamabad',
    'Lys': 'Lyon',
    'Um': 'Unknown',
    'Ixc': 'Chandigarh',
    'Re': 'Reims',
    'Vtz': 'Vishakhapatnam',
    'Ixz': 'Port Blair',
    'Khh': 'Kaohsiung',
    'Han': 'Hanoi',
    'Oit': 'Oita',
    'Cts': 'Sapporo',
    'Hel': 'Helsinki',
    'Fuk': 'Fukuoka',
    'San': 'San Diego',
    'Bho': 'Bhopal',
    'Ded': 'Dehradun',
    'Ixe': 'Mangalore',
    'Ixm': 'Mangalore',
    'Se': 'Seattle',
    'Atl': 'Atlanta',
    'Dfw': 'Dallas',
    'Rgn': 'Yangon',
    'Ntr': 'Monterrey',
    'Tas': 'Tashkent',
    'Nan': 'Nanning',
    'Las': 'Las Vegas',
    'Jog': 'Yogyakarta',
    'Sub': 'Bandung',
    'Bdj': 'Banjarmasin',
    'Bdo': 'Bandung',
    'Tkg': 'Tanjungkarang',
    'Bah': 'Nassau',
    'Mia': 'Miami',
    'Gyd': 'Baku',
    'Edi': 'Edinburgh',
    'Ist': 'Istanbul',
    'Syz': 'Shiraz',
    'Los': 'Lagos',
    'Osl': 'Oslo',
    'Sng': 'San Ignacio de Velasco',
    'Phl': 'Philadelphia',
    'Mco': 'Orlando',
    'Cnb': 'Coonamble',
    'Beg': 'Belgrade',
    'Dwc': 'Dubai',
    'Sof': 'Sofia',
    'Txl': 'Berlin',
    'Usm': 'Koh Samui',
    'Cbr': 'Canberra',
    'Ixg': 'Belgaum',
    'Dhm': 'Dharamshala',
    'Udr': 'Udaipur',
    'Ixb': 'Siliguri',
    'Dad': 'Da Nang',
    'Pqc': 'Praia',
    'Vca': 'Can Tho',
    'Hue': 'Hue',
    'Hui': 'Hue',
    'Mum': 'Mumbai'
}
